### ISSUE TITLE
  File "/usr/local/lib/python2.7/UserDict.py", line 40, in __getitem__     raise KeyError(key) KeyError: 'SECRET_KEY'

### ISSUE THREAD

**Issue by monajalal** [anitab-org/portal#370]
```
mona@Monas-MacBook-Pro:~/systers/portal/systers_portal $ docker-compose run web python systers_portal/manage.py migrate
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Pulling db (postgres:9.4)...
9.4: Pulling from library/postgres
2a72cbf407d6: Pull complete
21d844e096dd: Pull complete
91ed82aa0097: Pull complete
f8b468f60ebc: Pull complete
ee723e7e314c: Pull complete
9dd4856007eb: Pull complete
33de3feb0580: Pull complete
8c5b566609e9: Pull complete
dfb040c17c55: Pull complete
d1422b0248f2: Pull complete
0f8807e327a4: Pull complete
b78b2acc2804: Pull complete
42839ebca984: Pull complete
Digest: sha256:79f6ad278103df26b64647650c02274058f9f644169a039566cf64d4982206a1
Status: Downloaded newer image for postgres:9.4
Creating portal_db_1
Traceback (most recent call last):
  File "systers_portal/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/src/portal/systers_portal/systers_portal/settings/docker.py", line 1, in <module>
    from .base import *
  File "/usr/src/portal/systers_portal/systers_portal/settings/base.py", line 20, in <module>
    SECRET_KEY = os.environ['SECRET_KEY']
  File "/usr/local/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SECRET_KEY'
```

**Comment by Monal5031** [comment]
@monajalal Its not an issue, this is mentioned in the README in point number 9. PTAL there :smile:

**Comment by sa7i** [comment]
@monajalal `docker run -e SECRET_KEY=foobarbaz portal_web` from the Readme can be run to solve the SECRET_KEY error
